Remove br tag from title to fix search engine results
ShadowBlip/gamescope-dbus pull request #10
Opened 2024-08-21 23:12 UTC by strycore

When searching for gamescope_dbus on search engines, the results show newline characters likely caused by some bad parsing on Github's side.

![image](https://github.com/user-attachments/assets/99bff236-516a-412d-9ade-b1f0068aed59)

I moved the `<br>` tag outside of the `<h1>` title which should fix the issue next time the page is re-indexed.

Also updated Cargo.lock to the current release.

2024-08-22 04:26 UTC, pastaq approved these changes

2024-09-29 20:35 UTC, ShadowApex requested changes
Thanks for this! I've updated the GitHub action to automatically update and commit the `Cargo.lock` file, so if you can remove the lock file change from this PR, we can merge this in.

2024-09-30 18:45 UTC, strycore commented
I had to close VS Code and do the edit with Vim because VS Code kept reverting the version to 1.4.1 :sweat_smile:

2024-09-30 19:47 UTC, ShadowApex approved these changes

2024-09-30 19:48 UTC, merged